### ISSUE TITLE
"We value your privacy" - Agree-Button

### ISSUE THREAD

**Issue by cinema44** [interlark/ustvgo_downloader#12]
I'm using Ubuntu 20 with firefox. When I use firefox "I-dont-care-about-cookies" avoid those boxes.
When I run download.py or update.py with option no headless I still see this privacy box which disturbes process of collecting links or new key.
How do you suppress this dialog box?

Regards
Tom

**Comment by interlark** [comment]
I don't get such messages on Ubuntu 20.04.1 with Firefox 83.0 :)
I don't know why you get them, probably because of specific of your location. But if you say that extension helps you with it, you can add it, simply put
```python
driver.install_addon('/full/path/to/extension.xpi')
```
right before
```python
driver.get('https://ustvgo.tv/')
```
And also you can run
```bash
find ~/.mozilla -name *.xpi | xargs realpath
```
to get a full path list of your installed firefox addons.

**Comment by cinema44** [comment]
You're the best. I never expected any difference in this jungle of privacy information boxes in E.U. compared to the rest of the world. Thank you much! To use a VPN is the easiest option for anybody else with same issiue.
